Suppress highlighting inside strings for modes which have them
tarsius/outline-minor-faces pull request #2
Opened 2020-03-29 14:45 UTC by wi11dey

Thanks for writing this.

This PR makes it so strings like `"asdf ;;; jkl"` are not highlighted--only comments are. Previously, text inside strings in programming modes that matched `outline-minor-faces-regexp` were highlighted to the end of the line, including in the outline-minor-faces.el file itself:

![previous](https://user-images.githubusercontent.com/52264243/77851782-76483e80-71ca-11ea-83c8-62d312446f81.png)

This made for some confusing syntax highlighting, especially if your `outline-minor-faces-regexp` is set to something that is common in strings.

The way it works is that if `font-lock-keywords-only` is `nil` (true for modes that have strings and comments), a function is used as the matcher which checks if the matched text has already been fontified as a string, and returns `nil` if so. If keyword-only matching is on (true for text modes, etc.) then the regexp is used directly and there is no performance hit.

I've also changed `outline-minor-faces--font-lock-keywords` to a static variable rather than a function, since according to the [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Search_002dbased-Fontification.html#Search_002dbased-Fontification), Font Lock keywords with `eval` are evaluated only _once_ in a buffer so the effect is the same as running a function to get the matcher while being simpler.

2020-03-29 16:54 UTC, tarsius commented
Ha! I have been working on exactly the same code this afternoon...

2020-03-29 16:55 UTC, tarsius commented
> I've also changed outline-minor-faces--font-lock-keywords to a static variable

That should be done in a separate commit.

2020-03-29 17:02 UTC, tarsius requested changes

2020-03-29 17:02 UTC, tarsius commented on outline-minor-faces.el
> +  "Returns a matcher that matches REGEXP only if it is not found
The first sentence must completely fit on the first line. Maybe "Return a matcher that matches REGEXP only outside of strings." Generally if such a first (aka summary) sentence is not precise enough, then that information should be repeated and augmented in the text that follows, even if that leads to some duplicated information.

And there's no need to do this in a separate commit, just squash into the appropriate existing commit. Rewriting "history" (aka it's not actually history yet) is perfectly okay on feature branches, even when they are public.

2020-03-29 17:46 UTC, wi11dey commented
Thanks for the quick review! I've re-done the commits starting from master so that there's one for new functionality and one for function->var. Docstring should also be up to convention now

2020-04-04 15:49 UTC, tarsius commented
I've fixed how strings and comments are detected. Your implementation did not work for doc-strings at least.

2020-04-04 15:49 UTC, merged

2020-04-04 15:49 UTC, tarsius commented
Thanks!